In [1]:
import numpy as np

In [13]:
w_hh = np.full((3, 2), 1)  # illustration purposes only, returns an array of size 3x2 filled with all 1s
w_hx = np.full((3, 3), 9)  # illustration purposes only, returns an array of size 3x3 filled with all 9s

print ("w_hh: \n",w_hh)
print ("w_hh shape: ", w_hh.shape, "\n")

print ("w_hx: \n",w_hx)
print (" w_hx shape: ", w_hx.shape, "\n")

# Joining the arrays
# Option 1: concantenate - horizontal
w_h1 = np.concatenate((w_hh,w_hx), axis = 1)
print ("Concatenate \n", w_h1)
print ("w_h shape \n", w_h1.shape)

# Option 2: hstack
w_h2 = np.hstack((w_hh,w_hx))
print ("hstack \n", w_h2)
print ("w_h shape ", w_h2.shape, "\n")


w_hh: 
 [[1 1]
 [1 1]
 [1 1]]
w_hh shape:  (3, 2) 

w_hx: 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
 w_hx shape:  (3, 3) 

Concatenate 
 [[1 1 9 9 9]
 [1 1 9 9 9]
 [1 1 9 9 9]]
w_h shape 
 (3, 5)
hstack 
 [[1 1 9 9 9]
 [1 1 9 9 9]
 [1 1 9 9 9]]
w_h shape  (3, 5) 



In [17]:
# Create some more dummy data
h_t_prev = np.full((2, 1), 1)  # illustration purposes only, returns an array of size 2x1 filled with all 1s
x_t = np.full((3, 1), 9)       # illustration purposes only, returns an array of size 3x1 filled with all 9s

print ("h_t_prev \n", h_t_prev)
print ("h_t_prev shape ", h_t_prev.shape, "\n")

print ("x_t \n", x_t)
print ("x_t shape ", x_t.shape, "\n")

# Option 1 conatenate - vertical 
ax_1 = np.concatenate((h_t_prev, x_t),axis=0)
print ("ax_1 :\n",ax_1)
print ("ax_1 shape:",ax_1. shape, "\n")

# Option 2 vstack - vertical 
ax_2 = np.vstack((h_t_prev, x_t))
print ("ax_2 :\n",ax_2)
print ("ax_2 shape:",ax_2. shape, "\n")

h_t_prev 
 [[1]
 [1]]
h_t_prev shape  (2, 1) 

x_t 
 [[9]
 [9]
 [9]]
x_t shape  (3, 1) 

ax_1 :
 [[1]
 [1]
 [9]
 [9]
 [9]]
ax_1 shape: (5, 1) 

ax_2 :
 [[1]
 [1]
 [9]
 [9]
 [9]]
ax_2 shape: (5, 1) 



In [23]:
w_hh = np.full((3, 2), 1)  # returns an array of size 3x2 filled with all 1s
w_hx = np.full((3, 3), 9)  # returns an array of size 3x3 filled with all 9s
h_t_prev = np.full((2, 1), 1)  # returns an array of size 2x1 filled with all 1s
x_t = np.full((3, 1), 9)       # returns an array of size 3x1 filled with all 9s


# If you want to randomize the values, uncomment the next 4 lines

# w_hh = np.random.standard_normal((3,2))
# w_hx = np.random.standard_normal((3,3))
# h_t_prev = np.random.standard_normal((2,1))
# x_t = np.random.standard_normal((3,1))

# Results
# Formula 1
stack_1 = np.hstack((w_hh,w_hx))
stack_2 = np.vstack((h_t_prev, x_t))
print("\nFormula 1")
print ("Term1 \n",stack_1)
print ("Term2 \n",stack_2)
formula_1 = np.matmul(np.hstack((w_hh,w_hx)), np.vstack((h_t_prev, x_t)))
print("Output: \n", formula_1)

# Formula 2
mul_1 = np.matmul(w_hh,h_t_prev)
mul_2 = np.matmul(w_hx, x_t)
print("\nFormula 2")
print ("Term1 \n",mul_1)
print ("Term2 \n",mul_2)
formula_2 = np.matmul(w_hh, h_t_prev) + np.matmul(w_hx, x_t)
print("Output: \n", formula_2, "\n")

print("-- Verify --")
print("Results are the same :", np.allclose(formula_1, formula_2))




Formula 1
Term1 
 [[1 1 9 9 9]
 [1 1 9 9 9]
 [1 1 9 9 9]]
Term2 
 [[1]
 [1]
 [9]
 [9]
 [9]]
Output: 
 [[245]
 [245]
 [245]]

Formula 2
Term1 
 [[2]
 [2]
 [2]]
Term2 
 [[243]
 [243]
 [243]]
Output: 
 [[245]
 [245]
 [245]] 

-- Verify --
Results are the same : True
