#  Activation functions

In [2]:
import numpy as np 

## ReLU

In [3]:
z = np.array([[-1.25459881], [ 4.50714306], [ 2.31993942], [ 0.98658484], [-3.4398136 ]])
z

array([[-1.25459881],
       [ 4.50714306],
       [ 2.31993942],
       [ 0.98658484],
       [-3.4398136 ]])

In [4]:
h = z.copy()
h[h<0] = 0 
h

array([[0.        ],
       [4.50714306],
       [2.31993942],
       [0.98658484],
       [0.        ]])

In [5]:
def relu (z):
    result = z.copy()
    result[result < 0] =  0
    return result


In [6]:
print(relu(z))

[[0.        ]
 [4.50714306]
 [2.31993942]
 [0.98658484]
 [0.        ]]


## Softmax

In [7]:
z = np.array([9, 8, 11, 10, 8.5])

In [8]:
e_z = np.exp(z)
e_z


array([ 8103.08392758,  2980.95798704, 59874.1417152 , 22026.46579481,
        4914.7688403 ])

In [9]:
sum_e_z = np.sum(e_z)
e_z[0]/sum_e_z

np.float64(0.08276947985173956)

In [10]:
def softmax(z):
    e_z = np.exp(z)
    sum_e_z = np.sum(e_z)
    return e_z/sum_e_z

In [11]:
softmax([9, 8, 11, 10, 8.5])

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])

In [12]:
np.sum(softmax([9, 8, 11, 10, 8.5]))

np.float64(1.0)

## Dimensions: 1-D arrays vs 2-D column vectors

In [13]:
V = 5 # Vocabulary size
x_array = np.zeros(V) # x_array is array of zeros with the same size as V
x_array

array([0., 0., 0., 0., 0.])

In [14]:
x_array.shape

(5,)

In [15]:
x_column_vector = x_array.copy()
x_column_vector.shape = (V,1) # alternatively (x_array.shape[0], 1)
x_column_vector

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
x_column_vector.shape

(5, 1)