#  Activation functions

In [12]:
import numpy as np 

## ReLU

In [20]:
z = np.array([[-1.25459881], [ 4.50714306], [ 2.31993942], [ 0.98658484], [-3.4398136 ]])
z

array([[-1.25459881],
       [ 4.50714306],
       [ 2.31993942],
       [ 0.98658484],
       [-3.4398136 ]])

In [17]:
h = z.copy()
h[h<0] = 0 
h

array([[0.        ],
       [4.50714306],
       [2.31993942],
       [0.98658484],
       [0.        ]])

In [26]:
def relu (z):
    result = z.copy()
    result[result < 0] =  0
    return result


In [27]:
print(relu(z))

[[0.        ]
 [4.50714306]
 [2.31993942]
 [0.98658484]
 [0.        ]]


## Softmax

In [42]:
z = np.array([9, 8, 11, 10, 8.5])

In [43]:
e_z = np.exp(z)
e_z


array([ 8103.08392758,  2980.95798704, 59874.1417152 , 22026.46579481,
        4914.7688403 ])

In [44]:
sum_e_z = np.sum(e_z)
e_z[0]/sum_e_z

np.float64(0.08276947985173956)

In [48]:
def softmax(z):
    e_z = np.exp(z)
    sum_e_z = np.sum(e_z)
    return e_z/sum_e_z

In [49]:
softmax([9, 8, 11, 10, 8.5])

array([0.08276948, 0.03044919, 0.61158833, 0.22499077, 0.05020223])

In [50]:
np.sum(softmax([9, 8, 11, 10, 8.5]))

np.float64(1.0)